//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.RestaurantOrder")]
    public interface RestaurantOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RestaurantOrder/MakeOrder", ReplyAction="http://tempuri.org/RestaurantOrder/MakeOrderResponse")]
        int MakeOrder(string[] items);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RestaurantOrderChannel : IISClient.ServiceReference1.RestaurantOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestaurantOrderClient : System.ServiceModel.ClientBase<IISClient.ServiceReference1.RestaurantOrder>, IISClient.ServiceReference1.RestaurantOrder {
        
        public RestaurantOrderClient() {
        }
        
        public RestaurantOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestaurantOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int MakeOrder(string[] items) {
            return base.Channel.MakeOrder(items);
        }
    }
}
